name: PR Checklist2
description: Review PR tasks before submission
title: "[Bug]: "
labels: ["PR review"]
body:
  - type: checkboxes
    id: loc
    attributes:
      label:
      options:
        - label: Lines of code less than 500?
          required: true
  - type: checkboxes
    id: prefix
    attributes:
      label:
      description: feat, fix, regfix, refactor, chore
      options:
        - label: Title includes prefix?
          required: true
