name: PR Checklist2
description: Review PR tasks before submission
title: "[Bug]: "
labels: ["PR review"]
body:
  - type: checkboxes
    id: loc
    attributes:
      label: Lines of Code
      options:
        - label: Lines of code less than 500?
          required: true
    id: prefix
    attributes:
      label: Title includes correction prefix?
      description: feat:, fix:, regfix:, refactor:, chore:
      options:
        - label: Title includes prefix?
          required: true
